# Generated by Django 3.1.7 on 2021-03-15 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210311_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255)),
                ('account_id', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('DE', 'Debit'), ('CR', 'Credit')], default=None, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('core_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
    ]
