# Generated by Django 3.1.7 on 2021-03-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.FloatField(),
        ),
    ]
