# Generated by Django 3.1.7 on 2021-03-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210315_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='xero_journal_line_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='transactions',
            unique_together={('core_account', 'xero_journal_line_id')},
        ),
    ]
