# Generated by Django 3.1.7 on 2021-03-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210319_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_sync_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
