# Generated by Django 3.1.7 on 2021-03-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_account_last_sync_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='quickbooks_journal_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='transactions',
            unique_together={('core_account', 'xero_journal_line_id'), ('core_account', 'quickbooks_journal_number')},
        ),
    ]
