# Generated by Django 3.1.7 on 2021-03-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210319_1948'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactions',
            unique_together={('core_account', 'xero_journal_line_id')},
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='quickbooks_journal_number',
        ),
    ]
