# Generated by Django 3.1.7 on 2021-03-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210319_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='xero_journal_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
