# Generated by Django 3.1.7 on 2021-03-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_transactions_xero_journal_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='last_sync_date',
            new_name='quickbooks_last_sync_date',
        ),
        migrations.AddField(
            model_name='account',
            name='xero_last_journal_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='transactions',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='xero_journal_line_id',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='xero_journal_number',
        ),
    ]
