# Generated by Django 3.1.7 on 2021-03-20 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210319_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='core_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.account'),
        ),
    ]
